Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,11 @@ jobs:
            -not -path "./node_modules/*" \
            -not -name "README.md" \
            -not -name "CONTRIBUTING.md" \
-           -exec basename {} \; | grep -vE '^[a-z0-9]+(-[a-z0-9]+)*\.md$'|| true)
-           echo $?  
-           echo "Hello WOrld"
+           -exec basename {} \; | grep -vE '^[a-z0-9]+(-[a-z0-9]+)*\.md$'|| true)"
+           if [ -n "$invalid_files" ]; then
+            echo "The following Markdown filenames are not in kebab case:"
+            echo "$invalid_files"
+           else
+              echo "All Markdown filenames are in kebab case."
+           fi
 
